version: '3'

services:
  api-server:
    build: .
    ports:
      - '8080:8080'
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Pokemon09* 
      - MYSQL_DATABASE=university
